#!/usr/bin/env python3

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# encoding: utf-8
'''
wrydump -- Dump the AMT Data From A Machine

wrydump is a tool to extract the AMT data from a machine and display it

@author:     Adrian Hungate

@copyright:  2017 Ocado Technology. All rights reserved.

@license:    Apache 2.0

@contact:    adrian.hungate@ocado.com
'''

import sys
import wry.version
import wry.CLITool

__all__ = []
__version__ = wry.version.__VERSION__
__date__ = '2017-07-04'
__updated__ = '2018-03-12'



class wrydump(wry.CLITool.CLITool):
    '''
    CLI tool to configure KVM settings
    '''
    version = "v%s" % __version__
    build_date = str(__updated__)

    def extra_run(self):
        print(self.dev.dump())
        return 0


if __name__ == "__main__":
    sys.exit(wrydump().run())
