#!/usr/bin/env python3
import json

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# encoding: utf-8
'''
wryeth -- Get the ethernet settings

wryeth is a tool to return the ethernet settings

@author:     Adrian Hungate

@copyright:  2017 Ocado Technology. All rights reserved.

@license:    Apache 2.0

@contact:    adrian.hungate@ocado.com
'''

import sys
import wry.version
import wry.CLITool

__all__ = []
__version__ = wry.version.__VERSION__
__date__ = '2017-08-23'
__updated__ = '2018-03-12'


class wrynetboot(wry.CLITool.CLITool):
    '''
    CLI tool to get ethernet settings
    '''
    version = "v%s" % __version__
    build_date = str(__updated__)

    def extra_init(self):
        #self.parser.add_argument("-S", "--state", dest = "state", help = "set a new power state", default = None)
        pass

    def extra_parse(self, args):
        #self.state = args.state
        pass

    def extra_run(self):
        state = self.dev.eth.mac
        print("State:", state)
        return 0


if __name__ == "__main__":
    sys.exit(wrynetboot().run())
