#!/usr/bin/env python3
import json

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# encoding: utf-8
'''
wrypower -- Change machine power state

wrypower is a tool to cause an AMT machine to turn on, off or reboot

@author:     Adrian Hungate

@copyright:  2017 Ocado Technology. All rights reserved.

@license:    Apache 2.0

@contact:    adrian.hungate@ocado.com
'''

import sys
import wry.version
import wry.CLITool

__all__ = []
__version__ = wry.version.__VERSION__
__date__ = '2017-07-04'
__updated__ = '2018-03-12'


class wrynetboot(wry.CLITool.CLITool):
    '''
    CLI tool to configure KVM settings
    '''
    version = "v%s" % __version__
    build_date = str(__updated__)

    def extra_init(self):
        self.parser.add_argument("-S", "--state", dest = "state", help = "set a new power state", default = None)

    def extra_parse(self, args):
        self.state = args.state

    def extra_run(self):
        print("Current power state:", self.dev.power.state)
        print("Available states:", self.dev.power.available_states())
        if self.state != None:
            try:
                self.dev.power.request_power_state_change(int(self.state))
            except:
                if self.state == "on":
                    self.dev.power.turn_on()
                elif self.state == "off":
                    self.dev.power.turn_off()
                elif self.state == "reset":
                    self.dev.power.reset()
                else:
                    print("I do not know how to '%s' the power" % (self.state,))
        return 0


if __name__ == "__main__":
    sys.exit(wrynetboot().run())
